### PR TITLE
use forward ref to access the formik form

### PR DESCRIPTION
**Pull request by compojoom**
This is maybe a fix for https://github.com/flipbyte/formik-json-schema/issues/35

@easeq - what do you think?

### CODE REVIEW

**Comment by easeq** [comment]
Have you tested it? Does it work?

**Comment by compojoom** [comment]
Yes, i‘m using it. I could add an example with it

**Comment by easeq** [comment]
That would be great! Once you've pushed the example, if everything is ok I'll merge this PR.

**Comment by compojoom** [comment]
Added the example. 
I was not sure where to place it... I created a separate exampleFormSubmitOutside container where I start the form with the basic settings and just add a submit button outside of the rendered form. Let me know if it is ok, or if you want me to modify it.

**Comment by compojoom** [comment]
@easeq - would you mind releasing 0.2.6 with this change? I have a teammate who is on 0.2.5 and we need this change.

**Comment by easeq** [comment]
I've published 0.2.6

**Pull request merged**
